#!/system/bin/sh
# GooseDroid customize.sh - Install Display Script

ui_print "======================================"
ui_print "             __"
ui_print "        '.___()'  < GooseDroid"
ui_print "         \\ ,__\\   Chaos Engine"
ui_print "          \\_/'    Honk Honk..."
ui_print ""
ui_print "     GooseDroid installed successfully!"
ui_print ""
ui_print "     🔥 Features:"
ui_print "     – Random chaos notifications"
ui_print "     – Volume freak-outs (up/down)"
ui_print "     – Flashlight flickering"
ui_print "     – Simulates HOME key presses"
ui_print "     – Simulates BACK key presses"
ui_print "     – Random screen locking"
ui_print ""
ui_print "     Peace was never an option. 🔪"
ui_print "======================================"
ui_print ""
ui_print "🔍 Debug mode:"
ui_print "  Enable logging:"
ui_print "    touch /data/goosedroid/debug"
ui_print "  Disable logging:"
ui_print "    rm /data/goosedroid/debug"